### ISSUE TITLE
Error build my project using restinio from conan because of string_view

### ISSUE THREAD

**Issue by bonewell** [Stiffstream/restinio-conan#3]
Hello,

I use restinio from conan repository to build my project.
I get error: "<experimental/string_view> has been removed. Use <string_view> instead." when my source code starts to build.
How I understand it is because asio 1.12.0 doesn't support std::string_vew
You can see build logs here https://travis-ci.org/bonewell/moneybox/jobs/520154283#L1123

Thanks!

**Comment by eao197** [comment]
Hi!

I suppose you use RESTinio from bincrafters repository. This repo contains a rather old version of RESTinio. Can you try RESTinio from that repository: https://bintray.com/stiffstream/public/restinio%3Astiffstream ?
(there is some description: https://github.com/Stiffstream/restinio-conan).

**Comment by bonewell** [comment]
How I understand the issue is about standalone version of Asio 1.12.0. Fail is reproduced: https://travis-ci.org/bonewell/moneybox/jobs/521136111#L1171

**Comment by eao197** [comment]
As far as I can see, there are some newer versions of Asio in bincrafters repo. I'll try to change Asio's version in RESTinio conanfile.py to 1.12.2.

**Comment by eao197** [comment]
I've updated conanfile.py for RESTinio 0.4.8.6 here: https://bintray.com/stiffstream/public/restinio%3Astiffstream/0.4.8.6%3Astable#
Try this version please.

**Comment by bonewell** [comment]
PASSED. It works now. Thanks you!

**Comment by eao197** [comment]
Thanks for reporting this!
